[project]
name = "movenet"
version = "0.1.0"
description = "local implementation of movenet"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
  "imageio",
  "opencv-python",
  "tensorflow",
  "tensorflow_hub"
]
